# Permalinks
permalink:           pretty

# Setup
title:               'lightning'
url:                 https://github.com/giftmischer69/lightning
tagline:             'A lightning-fast Jekyll theme'
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              giftmischer69 | Bradley Taunt
  url:               https://github.com/giftmischer69
  email:             giftmischer69@protonmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/giftmischer69/lightning
